name: sup
description: notes

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera:
  path_provider:
  path:
  sqflite: ^1.3.0

  timeago: ^2.0.26
  intl: ^0.16.1

  tuple: ^1.0.3

  permission_handler: ^5.0.0

  file_picker:

  fuzzy: <1.0.0

  declarative_animated_list: ^0.0.2

  morpheus:

  shared_preferences:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Axiforma
      fonts:
        - asset: "fonts/Kastelov - Axiforma Regular.otf"
          style: normal
        - asset: "fonts/Kastelov - Axiforma Italic.otf"
          style: italic
        - asset: "fonts/Kastelov - Axiforma Black Italic.otf"
          style: italic
          weight: 900
        - asset: "fonts/Kastelov - Axiforma Black.otf"
          style: normal
          weight: 900
        - asset: "fonts/Kastelov - Axiforma Bold Italic.otf"
          style: italic
          weight: 700
        - asset: "fonts/Kastelov - Axiforma Bold.otf"
          style: normal
          weight: 700
        - asset: "fonts/Kastelov - Axiforma Book Italic.otf"
          style: italic
          weight: 300
        - asset: "fonts/Kastelov - Axiforma Book.otf"
          style: normal
          weight: 300
        - asset: "fonts/Kastelov - Axiforma ExtraBold Italic.otf"
          style: italic
          weight: 800
        - asset: "fonts/Kastelov - Axiforma ExtraBold.otf"
          style: normal
          weight: 800
        - asset: "fonts/Kastelov - Axiforma Light Italic.otf"
          style: italic
          weight: 200
        - asset: "fonts/Kastelov - Axiforma Light.otf"
          style: normal
          weight: 200
        - asset: "fonts/Kastelov - Axiforma Medium Italic.otf"
          style: italic
          weight: 500
        - asset: "fonts/Kastelov - Axiforma Medium.otf"
          style: normal
          weight: 500
        - asset: "fonts/Kastelov - Axiforma SemiBold Italic.otf"
          style: italic
          weight: 600
        - asset: "fonts/Kastelov - Axiforma SemiBold.otf"
          style: normal
          weight: 600
        - asset: "fonts/Kastelov - Axiforma Thin Italic.otf"
          style: italic
          weight: 100
        - asset: "fonts/Kastelov - Axiforma Thin.otf"
          style: normal
          weight: 100

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
